Controllers/CuposController.cs
using Microsoft.AspNetCore.Mvc;
using Parqueadero.Datos;
using Parqueadero.Models;
namespace Parqueadero.Controllers
{
    public class CuposController : Controller
    {
        CuposDatos _Cuposdatos = new CuposDatos();
        public IActionResult ListarCupos()
        {
            var oLista = _Cuposdatos.Listar();
            return View(oLista);
        }

        public IActionResult GuardarCupos() { 
        return View();
        }

        [HttpPost]
        public IActionResult GuardarCupos(CuposModel oCupos)
        {
            if (!ModelState.IsValid)
                return View();

            var respuesta = _Cuposdatos.Insertar(oCupos);
            if (respuesta)
                return RedirectToAction("ListarCupos");
            else
                return View();
        }

        public IActionResult EditarCupos(int Idcupo) // debe llamarse igual que como se declara en el boton
        {
            /*al darle editar en listar, se envia el id a este metodo, este metodo lo envia al metodo 
             de obtener id para tomar todos los datos del usuario, se guardan todos los atributos del usuario
            en ousuario y esos datos se envian a la vista, osea editarusuarios, llegan a la vista
            y mediante el model se ponen en los input con los nombres exactos y por eso se llenan automaticamente
            en el formulario*/
            var ocupos = _Cuposdatos.Consultar(Idcupo);

            return View(ocupos);
        }

        [HttpPost]
        public IActionResult EditarCupos(CuposModel ocupos)
        {

            if (!ModelState.IsValid)
                return View();


            var respuesta = _Cuposdatos.Modificar(ocupos);
            if (respuesta)
                return RedirectToAction("ListarCupos");
            else
                return View();
            return View();
        }

        public IActionResult EliminarCupos(int Idcupo)
        {

            var ocupos = _Cuposdatos.Consultar(Idcupo);

            return View(ocupos);
        }

        [HttpPost]  
        public IActionResult EliminarCupos(CuposModel oCupos)
        {

            var respuesta = _Cuposdatos.Eliminar(oCupos.Idcupo);
            if (respuesta)
                return RedirectToAction("ListarCupos");
            else
                return View();
            return View();
        }
    }
}

Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;
using Parqueadero.Datos;
using Parqueadero.Models;

namespace Parqueadero.Controllers
{
    public class EmpleadoController : Controller
    {
        private EmpleadoDatos _empleadoDatos = new EmpleadoDatos();
        public IActionResult ListarEmpleados()
        {
            var oLista = _empleadoDatos.Listar();
            return View(oLista);
        }

        public IActionResult GuardarEmpleados() {

            return View();
        
        }

        [HttpPost]
        public IActionResult GuardarEmpleados(EmpleadoModel oEmpleado)
        {
            if (!ModelState.IsValid)
                return View();

            var respuesta = _empleadoDatos.Guardar(oEmpleado);
            if (respuesta)
                return RedirectToAction("ListarEmpleados");
            else
                return View();
        }

        public IActionResult EditarEmpleados(int Idempleado)
        {

            var oempleado = _empleadoDatos.Obtener(Idempleado);

            return View(oempleado);
        }

        [HttpPost]
        public IActionResult EditarEmpleados(EmpleadoModel oempleado)
        {

            if (!ModelState.IsValid)
                return View();


            var respuesta = _empleadoDatos.Editar(oempleado);
            if (respuesta)
                return RedirectToAction("ListarEmpleados");
            else
                return View();
            return View();
        }

        public IActionResult EliminarEmpleados(int Idempleado)
        {

            var oempleado = _empleadoDatos.Obtener(Idempleado);

            return View(oempleado);
        }

        [HttpPost]
        public IActionResult EliminarEmpleados(EmpleadoModel oEmpleado)
        {

            var respuesta = _empleadoDatos.Eliminar(oEmpleado.Idempleado);
            if (respuesta)
                return RedirectToAction("ListarEmpleados");
            else
                return View();
            return View();
        }
    }

}

Controllers/EntregaController.cs
using Microsoft.AspNetCore.Mvc;
using Parqueadero;
using Parqueadero.Models;
using Parqueadero.Datos;
using System.Data.SqlClient;
using System.Data;

namespace Parqueadero.Controllers
{
    public class EntregaController : Controller
    {
        private EntregaDatos _entregaParqueaderoDatos = new EntregaDatos();
        private UsuarioDatos _usuarioDatos = new UsuarioDatos();
        private EmpleadoDatos _empleadoDatos = new EmpleadoDatos();
        private CuposDatos _cupoDatos = new CuposDatos();
        private VehiculosDatos _vehiculoDatos = new VehiculosDatos();
        private AsignacionDatos _asignacionDatos = new AsignacionDatos();
        public IActionResult ListarEntrega()
        {
            var oEntrega = _entregaParqueaderoDatos.Listar();
            return View(oEntrega);
        }

        public IActionResult AgregarEntrega()
        {
            var model = new EntregaModel
            {
                AsignacionesDisponibles = _asignacionDatos.Listar()
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult AgregarEntrega(EntregaModel oEntrega)
        {

            var respuesta = _entregaParqueaderoDatos.InsertarEntrega(oEntrega);
            if (respuesta)
            {
                var ListaEntrega = _entregaParqueaderoDatos.Listar();
                return View("ListarEntrega", ListaEntrega);
            }
            else
            {
                oEntrega.AsignacionesDisponibles = _asignacionDatos.Listar();
                return View(oEntrega);
            }
            return View();
        }

        [HttpGet]
        public IActionResult ObtenerDatosAsignacion(int idAsignacion)
        {
            var datosAsignacion = _asignacionDatos.Consultar(idAsignacion);
            if (datosAsignacion == null)
            {
                return NotFound();
            }
            return Json(new
            {
                idUsuario = datosAsignacion.IdUsuario,
                idEmpleado = datosAsignacion.IdEmpleado,
                idCupo = datosAsignacion.IdCupo,
                idVehiculo = datosAsignacion.IdVehiculo
            });


        }
    }
}

Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using Parqueadero.Datos;
using Parqueadero.Models;

namespace Parqueadero.Controllers
{
    public class UsuariosController : Controller
    {
        UsuarioDatos _UsuarioDatos = new UsuarioDatos();

        public IActionResult ListarUsuarios()
        {
            //La vista mostrará una lista de contactos
            var oLista = _UsuarioDatos.Listar();

            return View(oLista);
        }

        public IActionResult GuardarUsuarios()
        {
            //METODO SOLO DEVUELVE VISTA
            return View();
        }

        [HttpPost]
        public IActionResult GuardarUsuarios(UsuariosModel oUsuario)
        {
            //METODO RECIBE EL OBJETO PARA GUARDARLO EN BD
            if(!ModelState.IsValid)
                return View();  


            var respuesta = _UsuarioDatos.Guardar(oUsuario);
            if (respuesta)
                return RedirectToAction("ListarUsuarios");
            else 
                return View();
        }

        public IActionResult EditarUsuarios(int Idusuario)
        {
            /*al darle editar en listar, se envia el id a este metodo, este metodo lo envia al metodo 
             de obtener id para tomar todos los datos del usuario, se guardan todos los atributos del usuario
            en ousuario y esos datos se envian a la vista, osea editarusuarios, llegan a la vista
            y mediante el model se ponen en los input con los nombres exactos y por eso se llenan automaticamente
            en el formulario*/
            var ousuario = _UsuarioDatos.Obtener(Idusuario);

            return View(ousuario);
        }

        [HttpPost]
        public IActionResult EditarUsuarios(UsuariosModel oUsuario)     
        {
          
            if (!ModelState.IsValid)
                return View();


            var respuesta = _UsuarioDatos.EditarUsuarios(oUsuario);
            if (respuesta)
                return RedirectToAction("ListarUsuarios");
            else
                return View();
            return View();
        }

        public IActionResult EliminarUsuarios(int Idusuario)
        {
            
            var ousuario = _UsuarioDatos.Obtener(Idusuario);

            return View(ousuario);
        }

        [HttpPost]
        public IActionResult EliminarUsuarios(UsuariosModel oUsuario)
        {

            var respuesta = _UsuarioDatos.EliminarUsuarios(oUsuario.Idusuario);
            if (respuesta)
                return RedirectToAction("ListarUsuarios");
            else
                return View();
            return View();
        }
    }




}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Parqueadero</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Parqueadero.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/fontawesome.css" />
    <link rel="stylesheet" href="~/css/templatemo-574-mexant.css">
    <link rel="stylesheet" href="~/css/animate.css" />
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.css">
    <title>Botón Invisible</title>
    <style>
        .invisible {
            display: none; /* Oculta el botón y no ocupa espacio */
        }
    </style>
</head>
<body>
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><a asp-controller="Home" asp-action="Index">Home</a></li>
                            <li class="scroll-to-section"><a asp-controller="Usuarios" asp-action="ListarUsuarios">Usuarios</a></li>
                            <li class="scroll-to-section"><a asp-controller="Empleado" asp-action="ListarEmpleados">Empleados</a></li>
                            <li class="scroll-to-section"><a asp-controller="Cupos" asp-action="ListarCupos">Cupos</a></li>
                            <li class="scroll-to-section"><a asp-controller="Vehiculos" asp-action="Listar">Vehiculos</a></li>
                            <li class="scroll-to-section"><a asp-controller="Movimientos" asp-action="ListarMovimientos">Movimientos</a></li>
                            <li class="scroll-to-section"><a asp-controller="Asignacion" asp-action="ListarAsignaciones">Asignaciones</a></li>
                            <li class="scroll-to-section"><a asp-controller="Entrega" asp-action="ListarEntrega">Entrega</a></li>
                            <li class="scroll-to-section"><a asp-controller="ReporteMovimientos" asp-action="Index">Informe</a></li>
                           
                            <li class="invisible"><a asp-controller="ReporteMovimientos" asp-action="Index">Informe</a></li>
                        </ul>
                        <!-- ***** Logo Start ***** -->
                        <!-- <a href="index.html" class="logo">
                            <img class="imglogo" src="~/images/Logo-AutoPark-Ancho.png" alt="">
                        </a>-->
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/isotope.min.js"></script>
    <script src="~/js/owl-carousel.js"></script>
    <script src="~/js/tabs.js"></script>
    <script src="~/js/swiper.js"></script>
    <script src="js/custom.js"></script>
    <script>
        var interleaveOffset = 0.5;
        var swiperOptions = {
            loop: true,
            speed: 1000,
            grabCursor: true,
            watchSlidesProgress: true,
            mousewheelControl: true,
            keyboardControl: true,
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev"
            },
            on: {
                progress: function () {
                    var swiper = this;
                    for (var i = 0; i < swiper.slides.length; i++) {
                        var slideProgress = swiper.slides[i].progress;
                        var innerOffset = swiper.width * interleaveOffset;
                        var innerTranslate = slideProgress * innerOffset;
                        swiper.slides[i].querySelector(".slide-inner").style.transform =
                            "translate3d(" + innerTranslate + "px, 0, 0)";
                    }
                },
                touchStart: function () {
                    var swiper = this;
                    for (var i = 0; i < swiper.slides.length; i++) {
                        swiper.slides[i].style.transition = "";
                    }
                },
                setTransition: function (speed) {
                    var swiper = this;
                    for (var i = 0; i < swiper.slides.length; i++) {
                        swiper.slides[i].style.transition = speed + "ms";
                        swiper.slides[i].querySelector(".slide-inner").style.transition =
                            speed + "ms";
                    }
                }
            }
        };
        var swiper = new Swiper(".swiper-container", swiperOptions);
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>