Controllers/AsignacionController.cs
using Microsoft.AspNetCore.Mvc;
using Parqueadero.Datos;
using Parqueadero.Models;

namespace Parqueadero.Controllers
{
    public class AsignacionController : Controller
    {
        private AsignacionDatos _asignacionParqueaderoDatos = new AsignacionDatos();
        private UsuarioDatos _usuarioDatos = new UsuarioDatos();
        private EmpleadoDatos _empleadoDatos = new EmpleadoDatos();
        private CuposDatos _cupoDatos = new CuposDatos();
        private VehiculosDatos _vehiculoDatos = new VehiculosDatos();
        public IActionResult ListarAsignaciones()
        {
            var Asignaciones = _asignacionParqueaderoDatos.Listar();
            return View(Asignaciones);
        }

        public IActionResult GuardarAsignacion()
        {
            var model = new AsignacionModel
            {
                Usuarios = _usuarioDatos.Listar(),
                Empleados = _empleadoDatos.Listar(),
                Cupos = _cupoDatos.Listar(),
                Vehiculos = _vehiculoDatos.Listar()
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult GuardarAsignacion(AsignacionModel asignacion)
        {

            var respuesta = _asignacionParqueaderoDatos.Insertar(asignacion);
            if (respuesta)
            {
                var listaAsignaciones = _asignacionParqueaderoDatos.Listar();
                return View("ListarAsignaciones", listaAsignaciones);
            }
            else
            {
                
                asignacion.Usuarios = _usuarioDatos.Listar();
                asignacion.Empleados = _empleadoDatos.Listar();
                asignacion.Cupos = _cupoDatos.Listar();
                asignacion.Vehiculos = _vehiculoDatos.Listar();
                return View(asignacion);
            }
        }
        public IActionResult EditarAsignacion(int idasignacion)
        {
            var asignacion = _asignacionParqueaderoDatos.Consultar(idasignacion);

            
            if (asignacion == null)
            {
                return NotFound();
            }

            asignacion.Usuarios = _usuarioDatos.Listar();
            asignacion.Empleados = _empleadoDatos.Listar();
            asignacion.Cupos = _cupoDatos.Listar();
            asignacion.Vehiculos = _vehiculoDatos.Listar();

            return View(asignacion);
        }

        [HttpPost]
        public IActionResult EditarAsignacion(AsignacionModel asignacion)
        {
            

            var respuesta = _asignacionParqueaderoDatos.Modificar(asignacion);
            if (respuesta)
            {
                var listaAsignaciones = _asignacionParqueaderoDatos.Listar();
                return View("ListarAsignaciones", listaAsignaciones);
            }
            else
            {
                return View(asignacion);
            }


        }
        public IActionResult EliminarAsignacion(int Idasignacion)
        {

            var oasignacion = _asignacionParqueaderoDatos.Consultar(Idasignacion);

            return View(oasignacion);
        }

        [HttpPost]
        public IActionResult EliminarAsignacion(AsignacionModel oAsignacion)
        {

            var respuesta = _asignacionParqueaderoDatos.Eliminar(oAsignacion.IdAsignacion);
            if (respuesta)
                return RedirectToAction("ListarAsignaciones");
            else
                return View();
            return View();
        }
    }
}

Views/Asignacion/EditarAsignacion.cshtml
@model AsignacionModel
@{
    ViewData["Title"] = "EditarAsignacion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="calculator" style="margin-top: 0px; padding: 130px 0px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-heading">
                    <h6>Estado</h6>
                    <h4><i class="fa-solid fa-car-side"></i> Parqueadero </h4>
                </div>
                <div class="col-lg-12">
                    <div class="naccs">
                        <div class="tabs">
                            <div class="row">
                                <div class="col-lg-12">
                                    <form asp-action="EditarAsignacion" asp-controller="Asignacion" method="post">
                                        <input asp-for="IdAsignacion" type="hidden"/>
                                        <div class="mb-3">
                                            <label class="form-label">Id usuario</label>
                                            <input asp-for="IdUsuario" id="IdUsuario" type="text" class="form-control" placeholder="Fecha y Hora">
                                            <span asp-validation-for="IdUsuario" class="text-danger"></span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Usuario</label>
                                            <select asp-for="IdUsuario" class="form-control">
                                                <option value="">Seleccione un usuario</option>
                                                @foreach (var usuario in Model.Usuarios)
                                                {
                                                    <option value="@usuario.Idusuario">@usuario.Nombre</option>
                                                }
                                            </select>
                                            <span asp-validation-for="IdUsuario" class="text-danger"></span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Empleado</label>
                                            <select asp-for="IdEmpleado" class="form-control">
                                                <option value="">Seleccione un empleado</option>
                                                @foreach (var empleado in Model.Empleados)
                                                {
                                                    <option value="@empleado.Idempleado">@empleado.Nombre</option>
                                                }
                                            </select>
                                            <span asp-validation-for="IdEmpleado" class="text-danger"></span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Cupo</label>
                                            <select asp-for="IdCupo" class="form-control">
                                                <option value="">Seleccione un cupo</option>
                                                @foreach (var cupo in Model.Cupos)
                                                {
                                                    <option value="@cupo.Idcupo">@cupo.Numero</option>
                                                }
                                            </select>
                                            <span asp-validation-for="IdCupo" class="text-danger"></span>
                                        </div>
                                        
                                        <div class="mb-3">
                                            <label class="form-label">Vehículo</label>
                                            <select asp-for="IdVehiculo" class="form-control">
                                                <option value="">Seleccione un vehículo</option>
                                                @foreach (var vehiculo in Model.Vehiculos)
                                                {
                                                    <option value="@vehiculo.Idvehiculos">@vehiculo.Placa</option>
                                                }
                                            </select>
                                            <span asp-validation-for="IdVehiculo" class="text-danger"></span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Fecha y Hora</label>
                                            <input asp-for="FechaHoraAsignacion" id="FechaHora" type="datetime-local" class="form-control" placeholder="Fecha y Hora">
                                            <span asp-validation-for="FechaHoraAsignacion" class="text-danger"></span>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Guardar</button>
                                        <a asp-action="ListarAsignaciones" asp-controller="Asignacion" class="btn btn-warning">Volver a la lista</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var fechaHoraInput = document.getElementById('FechaHora');
        var ahora = new Date();

        var anio = ahora.getFullYear();
        var mes = ('0' + (ahora.getMonth() + 1)).slice(-2);
        var dia = ('0' + ahora.getDate()).slice(-2);
        var hora = ('0' + ahora.getHours()).slice(-2);
        var minutos = ('0' + ahora.getMinutes()).slice(-2);

        var fechaHoraActual = anio + '-' + mes + '-' + dia + 'T' + hora + ':' + minutos;

        fechaHoraInput.value = fechaHoraActual;
    });
</script>

Views/Asignacion/EliminarAsignacion.cshtml
@model AsignacionModel
@{
    ViewData["Title"] = "EliminarAsignacion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="calculator" style="margin-top: 0px; padding: 130px 0px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-heading">
                    <h6>Estado</h6>
                    <h4><i class="fa-solid fa-car-side"></i> Parqueadero </h4>
                </div>
                <div class="col-lg-12">
                    <div class="naccs">
                        <div class="tabs">
                            <div class="row">
                                <div class="col-lg-12">
                                    <form asp-action="EliminarAsignacion" asp-controller="Asignacion" method="post">
                                        <input asp-for="IdAsignacion" type="hidden" class="form-control">

                                        <div class="alert alert-danger" role="alert">
                                            ¿Desea eliminar el Ingreso @Html.DisplayTextFor(m => m.IdAsignacion) ?
                                        </div>

                                        <button type="submit" class="btn btn-danger">Eliminar</button>
                                        <a asp-action="ListarAsignaciones" asp-controller="Asignacion" class="btn btn-warning">Volver a la lista</a>
                                    </form> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Asignacion/GuardarAsignacion.cshtml
@model AsignacionModel
@{
    ViewData["Title"] = "GuardarAsignacion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="calculator" style="margin-top: 0px; padding: 130px 0px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-heading">
                    <h6>Estado</h6>
                    <h4><i class="fa-solid fa-car-side"></i> Parqueadero </h4>
                </div>
                <div class="col-lg-12">
                    <div class="naccs">
                        <div class="tabs">
                            <div class="row">
                                <div class="col-lg-12">
                                    <form asp-action="GuardarAsignacion" asp-controller="Asignacion" method="post">
                                        <div class="mb-3">
                                            <label class="form-label">Id Asignacion</label>
                                            <input asp-for="IdAsignacion" id="idasignacion" type="text" class="form-control" placeholder="Id Usuario">
                                            <span asp-validation-for="IdAsignacion" class="text-danger"></span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Usuario</label>
                                            <select asp-for="IdUsuario" class="form-control">
                                                <option value="">Seleccione un usuario</option>
                                                @foreach (var usuario in Model.Usuarios)
                                                {
                                                    <option value="@usuario.Idusuario">@usuario.Nombre</option>
                                                }
                                            </select>
                                            <span asp-validation-for="IdUsuario" class="text-danger"></span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Empleado</label>
                                            <select asp-for="IdEmpleado" class="form-control">
                                                <option value="">Seleccione un empleado</option>
                                                @foreach (var empleado in Model.Empleados)
                                                {
                                                    <option value="@empleado.Idempleado">@empleado.Nombre</option>
                                                }
                                            </select>
                                            <span asp-validation-for="IdEmpleado" class="text-danger"></span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Cupo</label>
                                            <select asp-for="IdCupo" class="form-control">
                                                <option value="">Seleccione un cupo</option>
                                                @foreach (var cupo in Model.Cupos)
                                                {
                                                    <option value="@cupo.Idcupo">@cupo.Numero</option>
                                                }
                                            </select>
                                            <span asp-validation-for="IdCupo" class="text-danger"></span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Vehículo</label>
                                            <select asp-for="IdVehiculo" class="form-control">
                                                <option value="">Seleccione un vehículo</option>
                                                @foreach (var vehiculo in Model.Vehiculos)
                                                {
                                                    <option value="@vehiculo.Idvehiculos">@vehiculo.Placa</option>
                                                }
                                            </select>
                                            <span asp-validation-for="IdVehiculo" class="text-danger"></span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Fecha</label>
                                            <input asp-for="FechaHoraAsignacion" type="datetime-local" class="form-control" placeholder="Tipo de movimiento">
                                            <span asp-validation-for="FechaHoraAsignacion" class="text-danger"></span>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Guardar</button>
                                        <a asp-action="ListarAsignaciones" asp-controller="Asignacion" class="btn btn-warning">Volver a la lista</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var fechaHoraInput = document.getElementById('FechaHora');
        var ahora = new Date();

        var anio = ahora.getFullYear();
        var mes = ('0' + (ahora.getMonth() + 1)).slice(-2);
        var dia = ('0' + ahora.getDate()).slice(-2);
        var hora = ('0' + ahora.getHours()).slice(-2);
        var minutos = ('0' + ahora.getMinutes()).slice(-2);

        var fechaHoraActual = anio + '-' + mes + '-' + dia + 'T' + hora + ':' + minutos;

        fechaHoraInput.value = fechaHoraActual;
    });
</script>

Views/Asignacion/ListarAsignaciones.cshtml
@model List<AsignacionModel>
@{
    ViewData["Title"] = "ListarAsignaciones";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="calculator" style="margin-top: 0px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-heading">
                    <h6>Tabla</h6>
                    <h4><i class="fa-solid fa-right-to-bracket"></i> Asignaciones Registrados</h4>
                </div>
                <div class="col-lg-12">
                    <div class="naccs">
                        <div class="tabs">
                            <div class="row">
                                <div class="col-lg-12">
                                    <a asp-action="GuardarAsignacion" asp-controller="Asignacion" class="btn btn-success"><i class="bi bi-plus-circle"></i> Crear Nuevo</a>
                                    @if (Model != null && Model.Any())
                                    {
                                        <table class="listado">
                                            <thead>
                                                <tr>
                                                    <th>Id Asignacion</th>
                                                    <th>Usuario</th>
                                                    <th>Empleado</th>
                                                    <th>Id Cupo</th>
                                                    <th>Placa</th>
                                                    <th>Fecha</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (var item in Model)
                                                {
                                                    <tr>   
                                                        <td>@item.IdAsignacion</td>
                                                        <td>@item.IdUsuario</td>
                                                        <td>@item.IdEmpleado</td>
                                                        <td>@item.IdCupo</td>
                                                        <td>@item.IdVehiculo</td>
                                                        <td>@item.FechaHoraAsignacion</td>
                                                        <td>
                                                            <a asp-action="EditarAsignacion" asp-controller="Asignacion" class="btn btn-primary" asp-route-Idasignacion="@item.IdAsignacion"><i class="bi bi-pen"></i>Editar</a>
                                                            <a asp-action="EliminarAsignacion" asp-controller="Asignacion" class="btn btn-danger" asp-route-Idasignacion="@item.IdAsignacion">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                                                    <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0" />
                                                                </svg>Eliminar
                                                            </a>
                                                        </td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    }
                                    else
                                    {
                                        <p>No hay datos para mostrar.</p>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>