Controllers/VehiculosController.cs
using Microsoft.AspNetCore.Mvc;
using Parqueadero.Datos;
using Parqueadero.Models;
using System.Collections.Generic;

namespace Parqueadero.Controllers
{
    public class VehiculosController : Controller
    {

        VehiculosDatos _vehiculosDatos = new VehiculosDatos();
        UsuarioDatos _usuariosDatos = new UsuarioDatos();
        public IActionResult Listar()
        {
            var oLista = _vehiculosDatos.Listar();
            return View(oLista);
        }

        public IActionResult GuardarVehiculos()
        {
            var model = new VehiculosModel
            {
                Usuarios = _usuariosDatos.Listar()
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult GuardarVehiculos(VehiculosModel oVehiculos)
        {
            /*if (!ModelState.IsValid)
            {
                oVehiculos.Usuarios = _usuariosDatos.Listar();
            }
                return View(oVehiculos);
            */
            var respuesta = _vehiculosDatos.Guardar(oVehiculos);
            if (respuesta)
                return RedirectToAction("Listar");
            else
                return View();
        }

        public IActionResult EditarVehiculos(int Idvehiculo) //Idvehiculo, porque asi lo declare en la vista asp-route-Idvehiculo
        {
            var oVehiculo = _vehiculosDatos.Obtener(Idvehiculo);
            return View(oVehiculo);
        }

        [HttpPost]
        public IActionResult EditarVehiculos(VehiculosModel oVehiculos)
        {
         /*   if (!ModelState.IsValid)
                return View();*/

            var Respuesta = _vehiculosDatos.EditarVehiculos(oVehiculos);
            if (Respuesta)
                return RedirectToAction("Listar");
            else return View();
            return View();
        }

        public IActionResult EliminarVehiculos(int Idvehiculo) // Idvehiculo, porque asi lo declare en la vista asp-route-Idvehiculo
        {
            var oVehiculos = _vehiculosDatos.Obtener(Idvehiculo);
            return View(oVehiculos);
        }

        [HttpPost]
        public IActionResult EliminarVehiculos(VehiculosModel oVehiculo) 
        {
            var respuesta = _vehiculosDatos.EliminarVehiculos(oVehiculo.Idvehiculos);
            if (respuesta)
                return RedirectToAction("Listar");
            else return View();
            return View();
        }
    }
}

Views/Vehiculos/EditarVehiculos.cshtml
@model VehiculosModel
@{
    ViewData["Title"] = "EditarVehiculos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="calculator" style="margin-top: 0px; padding: 130px 0px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-heading">
                    <h6>Editar</h6>
                    <h4><i class="fa-solid fa-car-side"></i> Cupos del parqueadero </h4>
                </div>
                <div class="col-lg-12">
                    <div class="naccs">
                        <div class="tabs">
                            <div class="row">
                                <div class="col-lg-12">
                                    <form asp-action="EditarVehiculos" asp-controller="Vehiculos" method="post">
                                        <input asp-for="Idvehiculos" type="hidden" class="form-control">
                                        <div class="mb-3">
                                            <label class="form-label">Placa</label>
                                            <input asp-for="Placa" type="text" class="form-control" aria-describedby="emailHelp">
                                            <span asp-validation-for="Placa" class="text-darger"> </span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Modelo</label>
                                            <input asp-for="Modelo" type="text" class="form-control">
                                            <span asp-validation-for="Modelo" class="text-darger"> </span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Id Usuario</label>
                                            <input asp-for="UsuarioId" type="text" class="form-control">
                                            <span asp-validation-for="UsuarioId" class="text-darger"> </span>
                                        </div>

                                        <button type="submit" class="btn btn-primary">Guardar</button>
                                        <a asp-action="Listar" asp-controller="Vehiculos" class="btn btn-warning">Volver a la lista</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Vehiculos/EliminarVehiculos.cshtml
@model VehiculosModel
@{
    ViewData["Title"] = "EliminarVehiculos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="calculator" style="margin-top: 0px; padding: 130px 0px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-heading">
                    <h6>Estado</h6>
                    <h4><i class="fa-solid fa-car-side"></i> Parqueadero </h4>
                </div>
                <div class="col-lg-12">
                    <div class="naccs">
                        <div class="tabs">
                            <div class="row">
                                <div class="col-lg-12">
                                    <form asp-action="EliminarVehiculos" asp-controller="Vehiculos" method="post">
                                        <input asp-for="Idvehiculos" type="hidden" class="form-control">

                                        <div class="alert alert-danger" role="alert">
                                            ¿Desea eliminar el Vehiculo @Html.DisplayTextFor(m => m.Idvehiculos) ?
                                        </div>

                                        <button type="submit" class="btn btn-danger">Eliminar</button>
                                        <a asp-action="Listar" asp-controller="Vehiculos" class="btn btn-warning">Volver a la lista</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Vehiculos/GuardarVehiculos.cshtml
@model VehiculosModel
@{
    ViewData["Title"] = "GuardarVehiculos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<section class="calculator" style="margin-top: 0px; padding: 130px 0px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-heading">
                    <h6>Estado</h6>
                    <h4><i class="fa-solid fa-car-side"></i> Parqueadero </h4>
                </div>
                <div class="col-lg-12">
                    <div class="naccs">
                        <div class="tabs">
                            <div class="row">
                                <div class="col-lg-12">
                                    <form asp-action="GuardarVehiculos" asp-controller="Vehiculos" method="post">
                                        <div class="mb-3">
                                            <label class="form-label">Placa</label>
                                            <input asp-for="Placa" type="text" class="form-control">
                                            <span asp-validation-for="Placa" class="text-darger"> </span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Modelo</label>
                                            <input asp-for="Modelo" type="text" class="form-control">
                                            <span asp-validation-for="Modelo" class="text-darger"> </span>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Usuario</label>
                                            <select asp-for="UsuarioId" class="form-control">
                                                <option value="">Seleccione un usuario</option>
                                                @foreach (var usuario in Model.Usuarios)
                                                {
                                                    <option value="@usuario.Idusuario">@usuario.Nombre</option>
                                                }
                                            </select>
                                            <span asp-validation-for="UsuarioId" class="text-danger"></span>
                                        </div>

                                        <button type="submit" class="btn btn-primary">Guardar</button>
                                        <a asp-action="Listar" asp-controller="Vehiculos" class="btn btn-warning">Volver a la lista</a>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Views/Vehiculos/Listar.cshtml
@model List<VehiculosModel>
@{
    ViewData["Title"] = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}   

<section class="calculator" style="margin-top: 0px;">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-heading">
                    <h6>Tabla</h6>
                    <h4><i class="fa-solid fa-right-to-bracket"></i>Gestión de vehículos</h4>
                </div>
                <div class="col-lg-12">
                    <div class="naccs">
                        <div class="tabs">
                            <div class="row">
                                <div class="col-lg-12">
                                    <a asp-action="GuardarVehiculos" asp-controller="Vehiculos" class="btn btn-success"><i class="bi bi-plus-circle"></i> Crear Nuevo</a>
                                    <table class="table table-striped table-dark">
                                        <thead>
                                            <tr>
                                                <th scope="col">Placa</th>
                                                <th scope="col">Modelo</th>
                                                <th scope="col">Id Propietario</th>
                                                <th scope="col">Accion</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>

                                                    <td>@item.Placa</td>
                                                    <td>@item.Modelo</td>
                                                    <td>@item.UsuarioId</td>
                                                    <td>
                                                        <a asp-action="EditarVehiculos" asp-controller="Vehiculos" class="btn btn-primary" asp-route-Idvehiculo="@item.Idvehiculos"><i class="bi bi-pen"></i>Editar</a>
                                                        <a asp-action="EliminarVehiculos" asp-controller="Vehiculos" class="btn btn-danger" asp-route-Idvehiculo="@item.Idvehiculos">
                                                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                                                <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5M8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5m3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0" />
                                                            </svg>Eliminar
                                                        </a>

                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>